### ISSUE TITLE
Different origins for visual and collision geometry

### ISSUE THREAD

**Issue by gavanderhoorn** [luminize/matilda_support#1]
`matilda_macro.xacro` seems to specify different `origin`s for the `visual` and `collision` geometry elements of `link_1` ([here](https://github.com/luminize/matilda_support/blob/12d66516c858b22e816bc7fd4d1ab2b6b3717c64/urdf/matilda_macro.xacro#L26)).

Collision geometry appears to be ok (so I don't believe this will influence planning), but the visualisation in RViz looks strange, as the robot geometry associated with `link_1` appears to be floating in space behind the robot.

**Comment by luminize** [comment]
yes, I see.
The matilda_moveit_config package shows no such thing so I hadn't noticed. I'm updating the matilda_macro.xacro
